version: "3.0"
services:
  nginx:
    image: nginx:1.16-alpine
    ports:
      - "8080:80"
    volumes:
      - "./app:/app:ro"
      - ".docker/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: .docker/php.docker
    image: webplayer/php
    volumes:
      - "./app:/app"
      - "/home/lev/Музыка:/app/resources/audio:ro"
    depends_on:
      - redis
  redis:
    image: redis:6.2.6-alpine3.14

