version: "3.0"
services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.docker
    image: doomer/webplayer:1.0-nginx
    ports:
      - "8080:80"
    volumes:
      - "./app:/app:ro"
      - ".docker/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: .docker/php.docker
    image: doomer/webplayer:1.0-php
    environment:
      - APP_ENV=dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - "./app:/app"
      - "/home/lev/Музыка:/app/public/audio:ro"
    depends_on:
      - redis
  redis:
    image: redis:6.2.6-alpine3.14

